--- 
- hosts: 172.31.29.176
  become: yes
  tasks:
      - include_tasks: myfile.yml
      
      - name: i want to install apache2
        apt:
          name: apache2
          state: present

      - name: i want to change the template
        template: 
           src: myindex.j2
           dest: /var/www/html/index.html
        notify: restartwebserver
  
  handlers:
      - name: restartwebserver
        services:
           name: apache2
           state: restarted