---
- hosts: mywebserver
  become: yes
  tasks:
     - name: i want install jdk8 on ubuntu server
       apt:
            name: "{{javajdk8onubuntu}}"
            state: present
       when: ansible_os_family=="Debian"

     - name: i want install jdk8 on redhat server
       yum:
            name: "{{javajdk8onredhat}}"
            state: present
       when: ansible_os_family=="RedHat"