---
- hosts: 172.31.29.176
  become: yes
  tasks:
     - name: i want exicute linux command
       command: hostname -f 
       register: myresult 
       
     - name: i want to display linux output
       debug: 
         msg: "{{myresult}}"