---
- hosts: 172.31.29.176
  become: yes
  vars: 
     myvar1: tree
     myvar2: git
     myvar3: wget
  tasks:
      - name: i want to display variable value
        debug: 
          msg: "{{myvar1}}"
      - name: i want to install pakeges
        apt:
            name: "{{item}}"
            state: present 
        when: ansible_os_family=="Debian"
        loop:
          - "{{myvar1}}"
          - "{{myvar2}}"
          - "{{myvar3}}"
