---
- hosts: all
  become: yes
  tasks:
          - name: i want install tree software
            apt:
                    name: tree
                    state: present

          - name: i want install wget software
            apt:
                    name: wget
                    state: present
